---
name: tmt Lint
on:  # yamllint disable-line rule:truthy
  pull_request:
  merge_group:
    branches:
      - main
    types:
      - checks_requested
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  tmt_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install podman
        run: |
          set -euxo pipefail
          sudo apt update
          sudo apt install -y podman

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: Run tmt Lint
        run: >
          podman run -it
          --volume ./${{ github.event.repository.name }}:/${{ github.event.repository.name }}:Z
          --workdir /${{ github.event.repository.name }}
          --rm quay.io/testing-farm/tmt
          tmt lint
