---
name: tmt Lint
on:  # yamllint disable-line rule:truthy
  pull_request:
  merge_group:
    branches:
      - main
    types:
      - checks_requested
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  tmt_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          path: ${{ github.event.repository.name }}

      - name: Run tmt Lint
        run: >
          podman run -it
          --volume ./${{ github.event.repository.name }}:/${{ github.event.repository.name }}:Z
          --workdir /${{ github.event.repository.name }}
          --rm quay.io/teemtee/tmt
          tmt lint
